/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A single playing card. */
export declare class Card {
  /** Parses a card such as `"As"`, `"Kh"`, `"Q♦"`, `"2c"`. */
  static parse(text: string): Card
  static fromRankSuit(rank: Rank, suit: Suit): Card
  get rank(): Rank
  get suit(): Suit
  isDealt(): boolean
  /** The raw Cactus Kev encoding of this card. */
  asU32(): number
  toString(): string
  equals(other: Card): boolean
}

/** An ordered pile of cards. */
export declare class Cards {
  /** Parses a space-separated pile such as `"6♠ 6♥ 9♣"`. */
  static parse(text: string): Cards
  /** A full, ordered 52-card deck. */
  static deck(): Cards
  get length(): number
  isEmpty(): boolean
  contains(card: Card): boolean
  areUnique(): boolean
  toArray(): Array<Card>
  toString(): string
}

/** The best five-card hand inside a larger pile, plus its rank. */
export declare class Eval {
  /**
   * Evaluates exactly seven cards, given as a string such as
   * `"6♠ 6♥ 9♣ 6♦ 5♥ 5♠ 8♠"`.
   */
  static fromSeven(text: string): Eval
  /** Evaluates exactly seven cards held in a [`Cards`] pile. */
  static fromCards(cards: Cards): Eval
  get handRank(): HandRank
  /** The winning five cards. */
  get bestFive(): Cards
  toString(): string
}

/**
 * The blinds, ante, and bring-in a table charges.
 *
 * Amounts are `i64` because `pkcore` stores chips as `usize`; napi-rs maps
 * `i64` to a plain JS `number`, exact below 2^53. See EPIC-85 Scope.
 */
export declare class ForcedBets {
  /** Blinds only. Ante and bring-in are zero. */
  constructor(smallBlind: number, bigBlind: number)
  static withAnte(smallBlind: number, bigBlind: number, ante: number): ForcedBets
  get smallBlind(): number
  get bigBlind(): number
  get ante(): number
  get bringIn(): number
}

/**
 * The strength of a five-card poker hand.
 *
 * `value` is the Cactus Kev rank: **lower is stronger**, 1 is a royal flush.
 */
export declare class HandRank {
  /** The Cactus Kev rank value. Lower is stronger; 1 is a royal flush. */
  get value(): number
  /** The hand category, such as `"FullHouse"`. */
  get name(): string
  /** The exact hand class, such as `"SixesOverFives"`. */
  get class(): string
  toString(): string
  equals(other: HandRank): boolean
}

/** One seated player's chips and state. */
export declare class Player {
  constructor(handle: string, chipsAmount: number)
  get handle(): string
  /** Remaining stack: chips not yet committed this round. */
  get chips(): number
  /** Chips committed to the current betting round. */
  get bet(): number
  /** Chips committed across every round of the current hand. */
  get chipsInPlay(): number
  /** Buy-in plus every reload since. */
  get withdrawn(): number
  /** The player's state, such as `"Ready"` or `"Bet(100)"`. */
  get state(): string
  /** Stack plus everything committed this hand. */
  totalChipCount(): number
  isActive(): boolean
  isAllIn(): boolean
  isInHand(): boolean
  hasBet(): boolean
  /** Adds chips to the stack and to `withdrawn`. Returns the new stack. */
  reload(amount: number): number
  toString(): string
}

/** One pot awarded to one or more seats, with the hand that won it. */
export declare class PotWin {
  get equity(): SeatEquity
  /** The chips in this pot. */
  get chips(): number
  /** The seat indices that won this pot. */
  get seats(): Array<number>
  get eval(): Eval
  get handRank(): HandRank
  toString(): string
}

/**
 * A card rank: ace down to deuce, plus `blank`.
 *
 * PyO3 exposes these as class attributes (`Rank.ACE`); napi-rs has no
 * equivalent, so they are static methods (`Rank.ace()`).
 */
export declare class Rank {
  static ace(): Rank
  static king(): Rank
  static queen(): Rank
  static jack(): Rank
  static ten(): Rank
  static nine(): Rank
  static eight(): Rank
  static seven(): Rank
  static six(): Rank
  static five(): Rank
  static four(): Rank
  static trey(): Rank
  static deuce(): Rank
  static blank(): Rank
  get value(): number
  /** The prime used by the Cactus Kev evaluator for this rank. */
  prime(): number
  /** The Cactus Kev bit flag for this rank. */
  bits(): number
  /** 0-based index: deuce is 0, ace is 12. */
  number(): number
  toString(): string
  equals(other: Rank): boolean
}

/** One chair at the table: a player plus their cards. */
export declare class Seat {
  constructor(player: Player)
  get player(): Player
  isEmpty(): boolean
  isActive(): boolean
  isInHand(): boolean
  toString(): string
}

/**
 * A chip amount and the seats that share it.
 *
 * More than one seat means a split pot.
 */
export declare class SeatEquity {
  get chips(): number
  /** The seat indices sharing this amount. */
  get seats(): Array<number>
  /** How many seats share this amount. Greater than 1 is a split pot. */
  countOnes(): number
  toString(): string
}

/** The ring of seats at a table, in order. */
export declare class Seats {
  /** An empty ring. Add chairs with `push`. */
  constructor()
  /** Builds a ring from player names, in order, each with the same stack. */
  static fromNames(names: Array<string>, startingChips: number): Seats
  /** Appends a chair to the ring. */
  push(seat: Seat): void
  /** The number of chairs, occupied or not. */
  get size(): number
  countOccupied(): number
  getSeat(index: number): Seat | null
  /** Every chip on the table, across all seats. */
  totalChipCount(): number
  /** The highest bet on the current street. */
  currentBet(): number
  isBettingComplete(): boolean
  toString(): string
}

/** A card suit. */
export declare class Suit {
  static spades(): Suit
  static hearts(): Suit
  static diamonds(): Suit
  static clubs(): Suit
  static blank(): Suit
  get value(): number
  symbol(): string
  letter(): string
  toString(): string
  equals(other: Suit): boolean
}

/** A poker table: the seats, the board, the pot, and the betting state. */
export declare class Table {
  /** A no-limit hold'em table built from a ring of seats. */
  static nlhFromSeats(seats: Seats, forced: ForcedBets): Table
  /** The number of chairs at the table. */
  seatCount(): number
  get seats(): Seats
  get name(): string
  get forced(): ForcedBets
  /** The betting phase, such as `"PreFlop"`. */
  get phase(): string
  get pot(): number
  /** The highest bet on the current street. */
  get bet(): number
  /** The dealer button seat index. */
  get button(): number
  get board(): Cards
  /** Every chip in the system: seats plus bets plus pot. */
  tableChipCount(): number
  /**
   * The chip total snapshotted when the hand began. `end_hand` compares
   * against it to catch chip-conservation failures.
   */
  get handChipTotal(): number
  countOccupiedSeats(): number
  isPreflop(): boolean
  isGameOver(): boolean
  minRaise(): number
  toString(): string
}

/**
 * Every pot awarded at the end of a hand, main pot first.
 *
 * There is deliberately no `total()` here: summing the pots is one line of JS,
 * and `pkcore.js` keeps all arithmetic in `pkcore`.
 */
export declare class Winnings {
  /** The number of pots awarded. More than one means a side pot. */
  get length(): number
  isEmpty(): boolean
  /** The main pot. */
  first(): PotWin
  /** The first side pot. */
  second(): PotWin
  toArray(): Array<PotWin>
  toString(): string
}

/**
 * The `pkcore` version this addon was compiled against.
 *
 * Safe to read off this crate's own version: the version-lockstep rule in
 * `CLAUDE.md` keeps them identical.
 */
export declare function pkcoreVersion(): string
