/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A single playing card. */
export declare class Card {
  /** Parses a card such as `"As"`, `"Kh"`, `"Q♦"`, `"2c"`. */
  static parse(text: string): Card
  static fromRankSuit(rank: Rank, suit: Suit): Card
  get rank(): Rank
  get suit(): Suit
  isDealt(): boolean
  /** The raw Cactus Kev encoding of this card. */
  asU32(): number
  toString(): string
  equals(other: Card): boolean
}

/** An ordered pile of cards. */
export declare class Cards {
  /** Parses a space-separated pile such as `"6♠ 6♥ 9♣"`. */
  static parse(text: string): Cards
  /** A full, ordered 52-card deck. */
  static deck(): Cards
  get length(): number
  isEmpty(): boolean
  contains(card: Card): boolean
  areUnique(): boolean
  toArray(): Array<Card>
  toString(): string
}

/** The best five-card hand inside a larger pile, plus its rank. */
export declare class Eval {
  /**
   * Evaluates exactly seven cards, given as a string such as
   * `"6♠ 6♥ 9♣ 6♦ 5♥ 5♠ 8♠"`.
   */
  static fromSeven(text: string): Eval
  /** Evaluates exactly seven cards held in a [`Cards`] pile. */
  static fromCards(cards: Cards): Eval
  get handRank(): HandRank
  /** The winning five cards. */
  get bestFive(): Cards
  toString(): string
}

/**
 * The strength of a five-card poker hand.
 *
 * `value` is the Cactus Kev rank: **lower is stronger**, 1 is a royal flush.
 */
export declare class HandRank {
  /** The Cactus Kev rank value. Lower is stronger; 1 is a royal flush. */
  get value(): number
  /** The hand category, such as `"FullHouse"`. */
  get name(): string
  /** The exact hand class, such as `"SixesOverFives"`. */
  get class(): string
  toString(): string
  equals(other: HandRank): boolean
}

/**
 * A card rank: ace down to deuce, plus `blank`.
 *
 * PyO3 exposes these as class attributes (`Rank.ACE`); napi-rs has no
 * equivalent, so they are static methods (`Rank.ace()`).
 */
export declare class Rank {
  static ace(): Rank
  static king(): Rank
  static queen(): Rank
  static jack(): Rank
  static ten(): Rank
  static nine(): Rank
  static eight(): Rank
  static seven(): Rank
  static six(): Rank
  static five(): Rank
  static four(): Rank
  static trey(): Rank
  static deuce(): Rank
  static blank(): Rank
  get value(): number
  /** The prime used by the Cactus Kev evaluator for this rank. */
  prime(): number
  /** The Cactus Kev bit flag for this rank. */
  bits(): number
  /** 0-based index: deuce is 0, ace is 12. */
  number(): number
  toString(): string
  equals(other: Rank): boolean
}

/** A card suit. */
export declare class Suit {
  static spades(): Suit
  static hearts(): Suit
  static diamonds(): Suit
  static clubs(): Suit
  static blank(): Suit
  get value(): number
  symbol(): string
  letter(): string
  toString(): string
  equals(other: Suit): boolean
}

/**
 * The `pkcore` version this addon was compiled against.
 *
 * Safe to read off this crate's own version: the version-lockstep rule in
 * `CLAUDE.md` keeps them identical.
 */
export declare function pkcoreVersion(): string
