/* auto-generated by NAPI-RS */
/* eslint-disable */
/** The five community cards: flop, turn, and river. */
export declare class Board {
  /** Parses five community cards, such as `"9♣ 6♦ 5♥ 5♠ 8♠"`. */
  static parse(text: string): Board
  /** The three flop cards. */
  get flop(): Cards
  get turn(): Card
  get river(): Card
  /** The four cards visible at the turn: flop plus turn. */
  turnCards(): Cards
  toString(): string
}

/** A single playing card. */
export declare class Card {
  /** Parses a card such as `"As"`, `"Kh"`, `"Q♦"`, `"2c"`. */
  static parse(text: string): Card
  static fromRankSuit(rank: Rank, suit: Suit): Card
  get rank(): Rank
  get suit(): Suit
  isDealt(): boolean
  /** The raw Cactus Kev encoding of this card. */
  asU32(): number
  toString(): string
  equals(other: Card): boolean
}

/** An ordered pile of cards. */
export declare class Cards {
  /** Parses a space-separated pile such as `"6♠ 6♥ 9♣"`. */
  static parse(text: string): Cards
  /** A full, ordered 52-card deck. */
  static deck(): Cards
  get length(): number
  isEmpty(): boolean
  contains(card: Card): boolean
  areUnique(): boolean
  toArray(): Array<Card>
  toString(): string
}

/**
 * Runs one hand at a table: seats players, deals, takes actions, pays out.
 *
 * Every method that changes the table takes `&mut self`, matching `pkcore`'s
 * own `Dealer`. `pkcore.py` had to make the same switch when EPIC-83 removed
 * the interior-mutability table.
 */
export declare class Dealer {
  /** A dealer with an empty no-limit hold'em table of `seat_count` chairs. */
  constructor(forced: ForcedBets, seatCount: number)
  /** A dealer for an already-built table. */
  static fromTable(table: Table): Dealer
  /** Seats a player in the first open chair. Returns the seat index. */
  seatPlayer(player: Player): number
  /** Seats a player in a named chair. */
  seatPlayerAt(player: Player, seat: number): void
  removePlayer(seat: number): Player
  /** Shuffles, posts blinds, and deals hole cards. */
  startHand(): void
  /** Collects bets and deals the next street. */
  advanceStreet(): void
  /** Resolves the showdown and pays out. */
  endHand(): Winnings
  bet(seat: number, amount: number): void
  call(seat: number): void
  check(seat: number): void
  /** Raises the total bet to `amount`, not by `amount`. */
  raiseTo(seat: number, amount: number): void
  allIn(seat: number): void
  fold(seat: number): void
  /**
   * Marks a seat ready for the next hand. Lobby management, not an in-hand
   * action.
   */
  ready(seat: number): void
  get table(): Table
  tableId(): string
  isHandInProgress(): boolean
  nextToAct(): number
  pot(): number
  /** The stack at a seat, or `null` if the chair is empty or out of range. */
  chipsAt(seat: number): number | null
  /**
   * Every event so far, oldest first.
   *
   * A plain array, not a `TableLog` wrapper class: arrays are native in JS.
   */
  eventLog(): Array<TableAction>
}

/** The best five-card hand inside a larger pile, plus its rank. */
export declare class Eval {
  /**
   * Evaluates exactly seven cards, given as a string such as
   * `"6♠ 6♥ 9♣ 6♦ 5♥ 5♠ 8♠"`.
   */
  static fromSeven(text: string): Eval
  /** Evaluates exactly seven cards held in a [`Cards`] pile. */
  static fromCards(cards: Cards): Eval
  get handRank(): HandRank
  /** The winning five cards. */
  get bestFive(): Cards
  toString(): string
}

/**
 * The blinds, ante, and bring-in a table charges.
 *
 * Amounts are `i64` because `pkcore` stores chips as `usize`; napi-rs maps
 * `i64` to a plain JS `number`, exact below 2^53. See EPIC-85 Scope.
 */
export declare class ForcedBets {
  /** Blinds only. Ante and bring-in are zero. */
  constructor(smallBlind: number, bigBlind: number)
  static withAnte(smallBlind: number, bigBlind: number, ante: number): ForcedBets
  get smallBlind(): number
  get bigBlind(): number
  get ante(): number
  get bringIn(): number
}

/**
 * The strength of a five-card poker hand.
 *
 * `value` is the Cactus Kev rank: **lower is stronger**, 1 is a royal flush.
 */
export declare class HandRank {
  /** The Cactus Kev rank value. Lower is stronger; 1 is a royal flush. */
  get value(): number
  /** The hand category, such as `"FullHouse"`. */
  get name(): string
  /** The exact hand class, such as `"SixesOverFives"`. */
  get class(): string
  toString(): string
  equals(other: HandRank): boolean
}

/** Every player's hole cards for one hand, in seat order. */
export declare class HoleCards {
  /** An empty set. Add hands with `push`. */
  constructor()
  /** Parses every player's hand, such as `"6♠ 6♥ 5♦ 5♣"` for two players. */
  static parse(text: string): HoleCards
  /** How many players have cards. */
  get length(): number
  isEmpty(): boolean
  /** One player's hand, or `null` if the index is past the end. */
  get(index: number): Two | null
  push(two: Two): void
  toArray(): Array<Two>
  toString(): string
}

/** One seated player's chips and state. */
export declare class Player {
  constructor(handle: string, chipsAmount: number)
  get handle(): string
  /** Remaining stack: chips not yet committed this round. */
  get chips(): number
  /** Chips committed to the current betting round. */
  get bet(): number
  /** Chips committed across every round of the current hand. */
  get chipsInPlay(): number
  /** Buy-in plus every reload since. */
  get withdrawn(): number
  /** The player's state, such as `"Ready"` or `"Bet(100)"`. */
  get state(): string
  /** Stack plus everything committed this hand. */
  totalChipCount(): number
  isActive(): boolean
  isAllIn(): boolean
  isInHand(): boolean
  hasBet(): boolean
  /** Adds chips to the stack and to `withdrawn`. Returns the new stack. */
  reload(amount: number): number
  toString(): string
}

/** What a player chooses to do when it is their turn. */
export declare class PlayerAction {
  static fold(): PlayerAction
  static check(): PlayerAction
  static call(): PlayerAction
  static allIn(): PlayerAction
  /** Opens a bet of `amount` chips. */
  static bet(amount: number): PlayerAction
  /** Raises the total bet **to** `amount`, not by `amount`. */
  static raise(amount: number): PlayerAction
  /** One of `"Fold"`, `"Check"`, `"Call"`, `"Bet"`, `"Raise"`, `"AllIn"`. */
  get kind(): string
  /** The chip amount for a bet or raise, otherwise `null`. */
  get amount(): number | null
  toString(): string
}

/**
 * A multi-hand game on one table: deal, act, showdown, repeat.
 *
 * `pkcore`'s `PokerSession::run_hand` takes a Rust closure. It is
 * deliberately **not** bound here. Calling a JS function from inside a
 * `&mut self` method would let that callback re-enter the same session object
 * and alias the mutable borrow, which is undefined behaviour. Drive the loop
 * from JS instead — it reads better anyway:
 *
 * ```js
 * session.startHand()
 * let seat
 * while ((seat = session.nextActor()) !== null) {
 *   session.applyAction(seat, PlayerAction.call())
 * }
 * const winnings = session.endHand()
 * ```
 */
export declare class PokerSession {
  constructor(table: Table)
  /** Shuffles, posts blinds, deals, and increments `handNumber`. */
  startHand(): void
  /**
   * The seat that must act next, or `null` when the betting is done.
   *
   * Deals the next street on its own when a betting round closes, so a
   * caller only ever loops on this one method.
   */
  nextActor(): number | null
  applyAction(seat: number, action: PlayerAction): void
  /** What the session needs next, without changing whose turn it is. */
  nextStep(): SessionStep
  /** Resolves the showdown and pays out. */
  endHand(): Winnings
  /**
   * Returns every committed chip and resets the table after a failed hand.
   * Returns the number of chips returned.
   */
  abortHand(): number
  isHandComplete(): boolean
  isHandInProgress(): boolean
  /** How many hands have been started. */
  get handNumber(): number
  get table(): Table
  /**
   * The full 52-card deck as shuffled at the start of the current hand, or
   * `null` before the first hand.
   */
  get shuffledDeck(): string | null
  /** Applies new blinds at the start of the next hand. */
  setBlinds(forced: ForcedBets): void
  /** Removes players with no chips. Returns the seats emptied. */
  eliminateBusted(): Array<number>
  /** How many seated players still have chips. */
  countFunded(): number
}

/** One pot awarded to one or more seats, with the hand that won it. */
export declare class PotWin {
  get equity(): SeatEquity
  /** The chips in this pot. */
  get chips(): number
  /** The seat indices that won this pot. */
  get seats(): Array<number>
  get eval(): Eval
  get handRank(): HandRank
  toString(): string
}

/**
 * A card rank: ace down to deuce, plus `blank`.
 *
 * PyO3 exposes these as class attributes (`Rank.ACE`); napi-rs has no
 * equivalent, so they are static methods (`Rank.ace()`).
 */
export declare class Rank {
  static ace(): Rank
  static king(): Rank
  static queen(): Rank
  static jack(): Rank
  static ten(): Rank
  static nine(): Rank
  static eight(): Rank
  static seven(): Rank
  static six(): Rank
  static five(): Rank
  static four(): Rank
  static trey(): Rank
  static deuce(): Rank
  static blank(): Rank
  get value(): number
  /** The prime used by the Cactus Kev evaluator for this rank. */
  prime(): number
  /** The Cactus Kev bit flag for this rank. */
  bits(): number
  /** 0-based index: deuce is 0, ace is 12. */
  number(): number
  toString(): string
  equals(other: Rank): boolean
}

/** One chair at the table: a player plus their cards. */
export declare class Seat {
  constructor(player: Player)
  get player(): Player
  isEmpty(): boolean
  isActive(): boolean
  isInHand(): boolean
  toString(): string
}

/**
 * A chip amount and the seats that share it.
 *
 * More than one seat means a split pot.
 */
export declare class SeatEquity {
  get chips(): number
  /** The seat indices sharing this amount. */
  get seats(): Array<number>
  /** How many seats share this amount. Greater than 1 is a split pot. */
  countOnes(): number
  toString(): string
}

/** The ring of seats at a table, in order. */
export declare class Seats {
  /** An empty ring. Add chairs with `push`. */
  constructor()
  /** Builds a ring from player names, in order, each with the same stack. */
  static fromNames(names: Array<string>, startingChips: number): Seats
  /** Appends a chair to the ring. */
  push(seat: Seat): void
  /** The number of chairs, occupied or not. */
  get size(): number
  countOccupied(): number
  getSeat(index: number): Seat | null
  /** Every chip on the table, across all seats. */
  totalChipCount(): number
  /** The highest bet on the current street. */
  currentBet(): number
  isBettingComplete(): boolean
  toString(): string
}

/**
 * What the session needs next.
 *
 * `kind` is `"PlayerToAct"` (read `seat`), `"StreetAdvanced"`,
 * `"HandComplete"`, or `"Failed"` (read `error`).
 */
export declare class SessionStep {
  get kind(): string
  /** The seat that must act, or `null` unless `kind` is `"PlayerToAct"`. */
  get seat(): number | null
  /**
   * Why the hand cannot continue, or `null` unless `kind` is `"Failed"`.
   *
   * A failed hand is **not** resolvable with `endHand`; call `abortHand`.
   */
  get error(): string | null
  isComplete(): boolean
}

/** A card suit. */
export declare class Suit {
  static spades(): Suit
  static hearts(): Suit
  static diamonds(): Suit
  static clubs(): Suit
  static blank(): Suit
  get value(): number
  symbol(): string
  letter(): string
  toString(): string
  equals(other: Suit): boolean
}

/** A poker table: the seats, the board, the pot, and the betting state. */
export declare class Table {
  /** A no-limit hold'em table built from a ring of seats. */
  static nlhFromSeats(seats: Seats, forced: ForcedBets): Table
  /** The number of chairs at the table. */
  seatCount(): number
  get seats(): Seats
  get name(): string
  get forced(): ForcedBets
  /** The betting phase, such as `"PreFlop"`. */
  get phase(): string
  get pot(): number
  /** The highest bet on the current street. */
  get bet(): number
  /** The dealer button seat index. */
  get button(): number
  get board(): Cards
  /** Every chip in the system: seats plus bets plus pot. */
  tableChipCount(): number
  /**
   * The chip total snapshotted when the hand began. `end_hand` compares
   * against it to catch chip-conservation failures.
   */
  get handChipTotal(): number
  countOccupiedSeats(): number
  isPreflop(): boolean
  isGameOver(): boolean
  minRaise(): number
  toString(): string
}

/**
 * One entry in a table's event log.
 *
 * The variants carry different payloads, so rather than binding forty classes
 * this exposes the shape `pkcore.py` settled on: a `kind` name plus the
 * optional `seat` and `amount` the event concerns.
 */
export declare class TableAction {
  /**
   * The event name, such as `"Bet"`, `"Fold"`, or `"DealtFlop"`.
   *
   * Read off the `Debug` form rather than a forty-arm match, so a new
   * `pkcore` variant appears here without a change to this crate.
   */
  get kind(): string
  /** The seat this event concerns, or `null`. */
  get seat(): number | null
  /** The chip amount this event concerns, or `null`. */
  get amount(): number | null
  toString(): string
}

/** One player's two hole cards. */
export declare class Two {
  /** Parses two cards, such as `"6♠ 6♥"` or `"AsKh"`. */
  static parse(text: string): Two
  static fromCards(first: Card, second: Card): Two
  get first(): Card
  get second(): Card
  containsCard(card: Card): boolean
  toString(): string
}

/**
 * Every pot awarded at the end of a hand, main pot first.
 *
 * There is deliberately no `total()` here: summing the pots is one line of JS,
 * and `pkcore.js` keeps all arithmetic in `pkcore`.
 */
export declare class Winnings {
  /** The number of pots awarded. More than one means a side pot. */
  get length(): number
  isEmpty(): boolean
  /** The main pot. */
  first(): PotWin
  /** The first side pot. */
  second(): PotWin
  toArray(): Array<PotWin>
  toString(): string
}

/**
 * The `pkcore` version this addon was compiled against.
 *
 * Safe to read off this crate's own version: the version-lockstep rule in
 * `CLAUDE.md` keeps them identical.
 */
export declare function pkcoreVersion(): string
